name: Publish on Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.TEMPLATE_API }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
